

POST https://curso.doardigital.com/webhook
content-type: application/json

{
 "event": "PAYMENT_CREATED",
 "payment": {
  "object": "payment",
  "id": "pay_7052493615378886",
  "dateCreated": "2023-03-13",
  "customer": "cus_000005179975",
  "paymentLink": null,
  "value": 29.04,
  "netValue": 27.05,
  "originalValue": null,
  "interestValue": null,
  "description": "fatura",
  "billingType": "BOLETO",
  "canBePaidAfterDueDate": true,
  "pixTransaction": null,
  "status": "PENDING",
  "dueDate": "2023-03-20",
  "originalDueDate": "2023-03-20",
  "paymentDate": null,
  "clientPaymentDate": null,
  "installmentNumber": null,
  "invoiceUrl": "https://sandbox.asaas.com/i/7052493615378886",
  "invoiceNumber": "01992104",
  "externalReference": "course_640f7785cb43d",
  "deleted": false,
  "anticipated": false,
  "anticipable": false,
  "creditDate": null,
  "estimatedCreditDate": null,
  "transactionReceiptUrl": null,
  "nossoNumero": "850373",
  "bankSlipUrl": "https://sandbox.asaas.com/b/pdf/7052493615378886",
  "lastInvoiceViewedDate": null,
  "lastBankSlipViewedDate": null,
  "discount": {
   "value": 0,
   "limitDate": null,
   "dueDateLimitDays": 0,
   "type": "PERCENTAGE"
  },
  "fine": {
   "value": 0,
   "type": "FIXED"
  },
  "interest": {
   "value": 0,
   "type": "PERCENTAGE"
  },
  "split": [
   {
    "id": "5a1a04e1-f067-41d1-97a1-6a8b7e8d8fcd",
    "walletId": "1854fa4d-da97-4ab0-8a51-152ec2c17833",
    "fixedValue": null,
    "percentualValue": 3.5,
    "totalValue": 0.94,
    "refusalReason": null,
    "status": "PENDING"
   }
  ],
  "postalService": false,
  "refunds": null
 }
}